---
title: "02_TissueSpecificAntigens_2021_Klk_1.0"
author: "Anouk Dupé, David Eckey, Dustin Schilling, Maria Yemane"
date: "25 4 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(affy)

library(vsn)

library(AnnotationDbi)

library(hgu133plus2hsenstcdf)
library(hgu133plus2hsenstprobe)

library(hexbin)
```

```{r}
# Setwd = Set working directory -> sets workspace to given folder path
setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/rawdata/rawdata breast GSE27830")
# read in CEL files
data.breast = ReadAffy()
data.breast@cdfName <- "HGU133Plus2_Hs_ENST"

orig=colnames(exprs(data.breast))
new = substr(orig, 1, nchar(orig) - 4)
colnames(exprs(data.breast)) = new

# Save image in different path by first defining new workspace and then saving the data
setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/sessions/rda")
save.image(file ="rawdata.breast.rda")
```

```{r}
# Quality control of data.breast
#-------------------------------

## Single chip control
image(data.breast, col=rainbow(100,start=0,end = 0.75)[100:1])

##Chips to exclude from further analysis
## - GSM687021 since there is a uncommon green sot on the left border



##GSM687017 - GSM687023 -> 10 chips (How do I exclude the GSM687021 chip)
setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/plots")
dev.copy2eps(file="QC_GSM687021.eps")

## Read in pheno Data

filenames = rownames(pData(data.breast))
samples = substr(filenames, 1, 9)
rownames(pData(data.breast)) =filenames
```


```{r}
## Normalization
breast.vsnrma <- vsnrma(data.breast)

setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/sessions/rda")
save.image(file = "normalized_data.rda")

## MeanSdPlot
meanSdPlot(breast.vsnrma)
###The line is approximately horizontal, so there shouldn't be a variance-mean dependence 

setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/plots")
dev.copy2eps(file="meanSdPlot_breast_vsnrma_normalized.eps")
```


```{r}
##Boxplot before normalization
x11(w=10, h=7)
par(las=2)

mmi=c(1,0.7,1.0477939,0.5366749)
par(mai=mmi)
boxplot(data.breast, col=rainbow(150),cex.axis=0.5,main="Gene expression in human breast cancer", las = 2)

setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/plots")
dev.copy2eps(file="boxplot_breast_rawdata.eps")


##Boxplot after normalization
x11(w=10, h=7)
par(las=2)
mmi=c(1,0.7,1.0477939,0.5366749)
par(mai=mmi)
boxplot(exprs(breast.vsnrma),col=rainbow(150),cex.axis=0.5,main="Gene expression in human breast cancer" , las=2)

setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/plots")
dev.copy2eps(file="boxplot_breast_rawdata_normalized.eps")
```
```{r}
## Density function before normalization
x11(w=10, h=7)
hist(data.breast, col=rainbow(150), main = "Density function of log Intensity of human breast cancer")

setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/plots")
dev.copy2eps(file="hist_breast_rawdata.eps")

## Density function after normalization
##vsnrma
eset = exprs(breast.vsnrma)

plot(density(eset[,1]), type="n", xlab="log Intensity", ylim=c(0,1), main = "Density function of log Intensity of human breast cancer")
for(i in 1:ncol(eset)){
  lines(density(eset[,i]), col=rainbow(150)[i])
}
```

```{r}
## RNA degeneration plot
#-----------------------

rnadeg.raw = AffyRNAdeg(data.breast)

plotAffyRNAdeg(rnadeg.raw, col = rainbow(150))
title(sub="human breast cancer rawdata")


dev.copy2eps(file="rnadeg.huan_breast_cancer.rawdata.eps")

plotAffyRNAdeg(rnadeg.raw, col = rainbow(150), transform = "shift.only")
title(sub="human breast cancer rawdata")

dev.copy2eps(file="rnadeg1.human_breast_cancer1.rawdata.eps")
```

```{r}
## Scatter plots
x11(w=9, h=5)
par(mfrow=c(1,2))


setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/plots")


for(i in 1:10){
  
plot(exprs(breast.vsnrma)[,c(i, i+1)], pch=".")
abline(0,1,col="red")

title(main=paste("Scaterplot of probe", substr(colnames(breast.vsnrma)[i],1,
nchar(colnames(breast.vsnrma)[i])-4),"and",substr(colnames(breast.vsnrma)[i+1],1,
nchar(colnames(breast.vsnrma)[i+1])-4), sep = " ", collapse = NULL))

permission = readline(prompt = "type y for next image: ")

if(permission == "y"){
  
}
else{
break}
}

file.name=paste("scatterplot_", as.character(substr(colnames(breast.vsnrma)[i], 1,
nchar(colnames(breast.vsnrma)[i])-4)),"_",as.character(substr(colnames(breast.vsnrma)[i+1],1,
nchar(colnames(breast.vsnrma)[i+1])-4)),".eps",sep="")

dev.copy2eps(file=file.name)
dev.off()

## None of the scatterplots seem to deviate significantly from the red line



```

```{r}

```


```{r}

setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/TRA Daten")

# Import of tra.human.5median
tra.human.5median=read.csv(file="Human_protein_atlas_TRA_5median_genes_annotated.tsv", sep=",")

# Import of tra.human
tra.human=read.csv(file="tra.2014.human.5x.table.tsv", sep="\t")

# Import of tra.human.roth
tra.human.roth=read.csv(file="tra.2014.human.roth.5x.table.tsv", sep="\t")

# Import of tra.mouse.4301
tra.mouse.4301=read.csv(file="tra.2014.mouse.4301.5x.table.tsv", sep="\t")

# Import of tra.human.gtex
tra.mouse.gtex=read.csv(file="tra.2017.human.gtex.5x.table.tsv", sep="\t")


```


```{r}
#Import of tra.mouse and location of Klk
setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/TRA Daten")


tra.mouse=read.csv(file="tra.2014.mouse.5x.table.tsv",sep="\t")
```


```{r}
# Filter all Klk from the TRA data sets

# For tra.human  
ind.human=grepl("^KLK",tra.human$gene.symbol)
ind.human =which(ind.human == TRUE)
Klk.TRA1 = as.data.frame(tra.human[ind.human,])

# For tra.human.5median ####DOESNT WORK SINCE CONFLICT DURING IMPORT
ind.5median=grepl("^Klk",tra.human.5median$gene.symbol)
ind.5median =which(ind.5median == TRUE)
Klk.TRA2 = as.data.frame(tra.human.5median[ind.5median,])

# For tra.human.roth
ind.roth=grepl("^KLK",tra.human.roth$gene.symbol)
ind.roth =which(ind.roth == TRUE)
Klk.TRA3 = as.data.frame(tra.human.roth[ind.roth,])

# For tra.mouse
ind.mouse=grepl("^Klk",tra.mouse$gene.symbol)
ind.mouse =which(ind.mouse == TRUE)
Klk.TRA4 = as.data.frame(tra.mouse[ind.mouse,])

# For tra.mouse.4301
ind.4301=grepl("^Klk",tra.mouse.4301$gene.symbol)
ind.4301 =which(ind.4301 == TRUE)
Klk.TRA5 = as.data.frame(tra.mouse.4301[ind.4301,])

# For tra.mouse.gtex ###Here the genes are listed in ensembl.symbol 
#-> should rearrange all genes in same columns before putting it all in one data frame 
ind.gtex=grepl("^KLK",tra.mouse.gtex$ensembl.symbol)
ind.gtex=which(ind.gtex == TRUE)
Klk.TRA6=as.data.frame(tra.mouse.gtex[ind.gtex,])

```

```{r}

setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/rawdata/GSE65216 breast cancer TNBC Her2 LumA LumB")
# Reading in klk breast cancer data set
data.Klk.breast=ReadAffy()

data.Klk.breast.norm=vsnrma(data.Klk.breast)
data.Klk.breast.matrix=exprs(data.Klk.breast.norm)


setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of skin specific genes in skin cancer/tables")

#read in ensembl annotation file
annotation.103 = read.csv("ensembl.103.txt",sep="\t")

setwd("/Users/Dusti/Documents/Studium/Bioinfo/Data_Analysis/Bioinformatik TRA Projekt/The role of Klk in cancer/sessions/rda")

#Setting up annotation
affy.ensembl=as.character(annotation.103[,5])
symbol.ensembl=as.character(annotation.103[,4])

names(symbol.ensembl) =affy.ensembl


affyIDs =rownames(data.Klk.breast.matrix)
symbol=symbol.ensembl[affyIDs]

head(symbol)

dim(data.Klk.breast.matrix)

length(symbol) ##same length as data.breast.matrix

#re-apply rownames to gene symbols in the data.matrix

rownames(data.Klk.breast.matrix)=as.character(symbol)

head(data.Klk.breast.matrix) # Matrix to work with

```

```{r}
## Selecting from the vector symbol genes of Klk

# Tissue in prostate as an example -> Here do the process with combined TRA data set

#But firstly executing it on whole TRA mouse dataset
tiss=tra.human[,11]

ind.prostate=which(tiss=="Prostate")

TRA.symbol=tra.human[,3]

prostate.TRA1=TRA.symbol[ind.prostate]

row.ind=which(as.character(symbol) %in% toupper(prostate.TRA1))

data.breast.matrix.prostate =data.Klk.breast.matrix[row.ind,] 
#How many do we got, just in the case of prostate Tissue in tra.human
dim(data.breast.matrix.prostate) #93 genes

# Extract the expression values for your genes with


```




